-- MySQL Script generated by MySQL Workbench
-- Wed Dec 28 11:03:21 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users` ;

CREATE TABLE IF NOT EXISTS `users` (
  `id_users` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `surname` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `role` TINYINT(3) NOT NULL DEFAULT 0 COMMENT '0_autor\n1_recenzent\n2_administrator',
  `created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted` TINYINT(2) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_users`),
  UNIQUE INDEX `id_users_UNIQUE` (`id_users` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contributions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `contributions` ;

CREATE TABLE IF NOT EXISTS `contributions` (
  `id_contributions` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `abstract` TEXT NULL,
  `id_users` INT NOT NULL,
  `state` TINYINT(3) NOT NULL COMMENT '0_ v recenznim rizeni\n1_ prijat\n2_ odmitnut',
  `created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted` TINYINT(2) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_contributions`),
  UNIQUE INDEX `id_contributions_UNIQUE` (`id_contributions` ASC),
  INDEX `fk_contributions_users_id_user_idx` (`id_users` ASC),
  CONSTRAINT `fk_contributions_users_id_user`
    FOREIGN KEY (`id_users`)
    REFERENCES `users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reviews`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reviews` ;

CREATE TABLE IF NOT EXISTS `reviews` (
  `id_reviews` INT NOT NULL AUTO_INCREMENT,
  `id_users` INT NOT NULL,
  `id_contributions` INT NOT NULL,
  `abstract_review` TINYINT(11) NULL,
  `topic_review` TINYINT(3) NULL,
  `author_review` TINYINT(3) NULL,
  `comment` TEXT NULL,
  `type` TINYINT(2) NOT NULL COMMENT '0_ normal - od recenzenta pri recenzi\n1_ final - od admina pri odmitnuti',
  `created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted` TINYINT(2) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_reviews`),
  UNIQUE INDEX `id_reviews_UNIQUE` (`id_reviews` ASC),
  INDEX `fk_reviews_users_idx` (`id_users` ASC),
  INDEX `fk_reviews_users_id_contributions_idx` (`id_contributions` ASC),
  CONSTRAINT `fk_reviews_users_id_users`
    FOREIGN KEY (`id_users`)
    REFERENCES `users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reviews_users_id_contributions`
    FOREIGN KEY (`id_contributions`)
    REFERENCES `contributions` (`id_contributions`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contributions_files`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `contributions_files` ;

CREATE TABLE IF NOT EXISTS `contributions_files` (
  `id_contributions_files` INT NOT NULL AUTO_INCREMENT,
  `id_contributions` INT NOT NULL,
  `file` BLOB NULL,
  `created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted` TINYINT(2) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_contributions_files`),
  UNIQUE INDEX `id_reviews_UNIQUE` (`id_contributions_files` ASC),
  INDEX `fk_contributions_files_reviews_id_contributions_idx` (`id_contributions` ASC),
  CONSTRAINT `fk_contributions_files_reviews_id_contributions`
    FOREIGN KEY (`id_contributions`)
    REFERENCES `contributions` (`id_contributions`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reviews_assignments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reviews_assignments` ;

CREATE TABLE IF NOT EXISTS `reviews_assignments` (
  `id_reviews_assignments` INT NOT NULL AUTO_INCREMENT,
  `id_users` INT NOT NULL,
  `id_contributions` INT NOT NULL,
  `state` TINYINT(2) NOT NULL COMMENT '0_ hotovo - recenze je napsana\n1_ pracujes se - recenze byla pridelena adminem recenzentovi',
  `created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted` TINYINT(2) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_reviews_assignments`),
  UNIQUE INDEX `id_reviews_UNIQUE` (`id_reviews_assignments` ASC),
  INDEX `fk_reviews_assignements_users_id_users_idx` (`id_users` ASC),
  INDEX `fk_reviews_assignements_users_id_contributions_idx` (`id_contributions` ASC),
  CONSTRAINT `fk_reviews_assignements_users_id_users`
    FOREIGN KEY (`id_users`)
    REFERENCES `users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reviews_assignements_users_id_contributions`
    FOREIGN KEY (`id_contributions`)
    REFERENCES `contributions` (`id_contributions`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `users`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `users` (`id_users`, `name`, `surname`, `email`, `password`, `role`, `created`, `deleted`) VALUES (1, 'JmenoAutor', 'PrijmeniAutor', 'autor@email.cz', NULL, 0, now(), 0);

COMMIT;

